const constants = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    INCREMENT_ITEM_AMOUT: "INCREMENT_ITEM_AMOUT",
    REDUCE_ITEM_AMOUT: "REDUCE_ITEM_AMOUT",
    INCREMENT_ITEMS_AMOUT: "INCREMENT_ITEMS_AMOUT",
    REDUCE_ITEMS_AMOUT: "REDUCE_ITEMS_AMOUT",
    ADD_TO_SELECT_ITEM:"ADD_TO_SELECT_ITEM",
    REMOVE_FROM_SELECT_ITEM:"REMOVE_FROM_SELECT_ITEM",
}

export default constants